name: SpinTest
version: 1.0.0
author: Ryotackey
description: test plugin
main: me.ryotackey.spintest.spintest
commands:
  test:
    description: Spintest command
    usage: /<command>
    default: true